### PR TITLE
Allow parsing of version 9 and newer files

### PR DESCRIPTION
**Pull request by gbm19**
The submitted code should be able to read most of version 9 and newer files.
Also, code has been added/changed to avoid program freezing when parsing unsupported files.

### CODE REVIEW

**Comment by Saluev** [comment]
Hello, @gbm19!
Thanks a lot for the contribution, this looks really impressive!
Before I start reviewing, could you please attach some test cases?

**Comment by FilipDominec** [comment]
I appreciate this fix - liborigin has often crashed on my system when I opened Origin 9 files. Thank you a lot.

**Comment by gbm19** [comment]
Test cases that ...
... work:
  http://blog.originlab.com/graphing/bubble-plot-on-google-map
  http://blog.originlab.com/wp-content/uploads/2017/02/SalmonPopulation.zip

  http://blog.originlab.com/graphing/display-date-and-time-tick-labels-in-multiple-lines
  http://blog.originlab.com/wp-content/uploads/2016/12/DateTickLabel.zip

  http://blog.originlab.com/graphing/manhattan-plots-in-origin-2017
  http://blog.originlab.com/wp-content/uploads/2016/09/ManhattanSample4Blog.zip

  http://blog.originlab.com/graphing/latex-improvements-in-origin-2017
  http://blog.originlab.com/wp-content/uploads/2016/10/LaTeX2017Blog.zip

... fail partially:
  http://blog.originlab.com/graphing/making-dynamic-inset-graphs
  http://blog.originlab.com/wp-content/uploads/2016/01/Zoom.zip

  http://blog.originlab.com/data-analysis/sequentially-initialize-fitting-parameters-in-batch-peak-analysis
  http://blog.originlab.com/wp-content/uploads/2016/10/ESRdata.zip

  http://blog.originlab.com/graphing/dynamic-data-exchange-dde-with-excel-workbooks-in-origin-2017
  http://blog.originlab.com/wp-content/uploads/2016/07/SampleExcelOPJ.zip

Failure is mainly due to (yet to be resolved) problems at the end of Origin800Parser::readGraphInfo().
Despite this problems, the new program does not freeze and reads data columns correctly for all files I tried.

If you are only interested in getting the DataColumn values in python, an alternative to this code
would be to use the module at  https://github.com/highperformancecoder/scidavis/tree/origin_import/importOPJ

**Comment by gbm19** [comment]
Closing this pull request. Got a much better solution.

**Comment by Saluev** [comment]
Are you going to share it? :)
Also, was anything particularly wrong with the changes proposed in this PR?

**Comment by gbm19** [comment]
Yes, have a little patience.
No, there is nothing wrong. It is only that it was quite difficult to solve the remaining problems while keeping the same procedure of the  OriginNNNParser.cpp files.
I find it easier to do the parsing in two separate steps. First split the file into related pieces and then get/interpret the relevant properties of each piece.

**Pull request closed without merging**
